/*
 * Large numeric faces, generated by tools/gen_fonts.sh.
 *
 * DIGITS ONLY: " !%+,-./0-9:" and nothing else. A glyph missing from an LVGL
 * font draws as nothing at all, so a label rendered with one of these must
 * only ever receive characters from that set -- which is exactly what
 * ui_fmt_value's `numeric_only` out-param is for. Durations ("3d 4h") and
 * booleans ("UP") set it false and must fall back to a text face.
 */
#pragma once

#include "lvgl.h"

extern const lv_font_t font_num_44;   /* 1x1 tile value, gauge centre */
extern const lv_font_t font_num_64;   /* 2x1 tile value */
extern const lv_font_t font_num_96;   /* 2x2 hero value, detail view */
